// <auto-generated />
using System;
using IssueTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.Infrastructure.Migrations
{
    [DbContext(typeof(IssueTrackerContext))]
    [Migration("20260111001826_AddClientInfo")]
    partial class AddClientInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IssueTracker.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "test@example.com",
                            EmployeeName = "Test User",
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "sarveesh@macs.com",
                            EmployeeName = "Sarveesh",
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "nigesh@macs.com",
                            EmployeeName = "Nigesh",
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "keerthii@macs.com",
                            EmployeeName = "Keerthii",
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "hanumanth@macs.com",
                            EmployeeName = "Hanumanth",
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "gowtham@macs.com",
                            EmployeeName = "Gowtham",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            ColorCode = "red",
                            PriorityName = "High"
                        },
                        new
                        {
                            PriorityId = 2,
                            ColorCode = "orange",
                            PriorityName = "Medium"
                        },
                        new
                        {
                            PriorityId = 3,
                            ColorCode = "blue",
                            PriorityName = "Low"
                        });
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Developer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "QA"
                        });
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Priority = 0,
                            Severity = 0,
                            StatusName = "Open"
                        },
                        new
                        {
                            StatusId = 2,
                            Priority = 0,
                            Severity = 0,
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusId = 3,
                            Priority = 0,
                            Severity = 0,
                            StatusName = "Closed"
                        });
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("IssueId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CompanyName = "Internal",
                            Email = "test@example.com",
                            EmployeeId = 1,
                            Name = "Test User",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 2,
                            CompanyName = "ClientCo",
                            Email = "client@example.com",
                            Name = "Client User",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 3,
                            CompanyName = "MACS",
                            Email = "sarveesh@macs.com",
                            EmployeeId = 2,
                            Name = "Sarveesh",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 4,
                            CompanyName = "MACS",
                            Email = "nigesh@macs.com",
                            EmployeeId = 3,
                            Name = "Nigesh",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 5,
                            CompanyName = "MACS",
                            Email = "keerthii@macs.com",
                            EmployeeId = 4,
                            Name = "Keerthii",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 6,
                            CompanyName = "MACS",
                            Email = "hanumanth@macs.com",
                            EmployeeId = 5,
                            Name = "Hanumanth",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 7,
                            CompanyName = "MACS",
                            Email = "gowtham@macs.com",
                            EmployeeId = 6,
                            Name = "Gowtham",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        },
                        new
                        {
                            UserId = 8,
                            CompanyName = "Perfect Solutions",
                            Email = "ramesh@perfect.com",
                            Name = "Ramesh",
                            PasswordHash = "$2a$11$CVJWrntWvcle3j8edkbb4OqBP.bnEvopHJ1g2lTXk6YdkBbu3OWvS"
                        });
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Comment", b =>
                {
                    b.HasOne("IssueTracker.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IssueTracker.Domain.Entities.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssueTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Employee", b =>
                {
                    b.HasOne("IssueTracker.Domain.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Issue", b =>
                {
                    b.HasOne("IssueTracker.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("IssueTracker.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssueTracker.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Task", b =>
                {
                    b.HasOne("IssueTracker.Domain.Entities.Employee", "AssignedEmployee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedTo");

                    b.HasOne("IssueTracker.Domain.Entities.Issue", "Issue")
                        .WithMany("Tasks")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssueTracker.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssueTracker.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Issue");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.User", b =>
                {
                    b.HasOne("IssueTracker.Domain.Entities.Employee", "Employee")
                        .WithMany("LinkedUsers")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("LinkedUsers");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IssueTracker.Domain.Entities.Task", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
